# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('pw_hash', models.CharField(max_length=60)),
                ('created_at', models.CharField(max_length=60)),
                ('updated_at', models.CharField(max_length=60)),
            ],
        ),
    ]
